package org.bertspark.kafka.simulator

import org.bertspark.nlp.medical.MedicalCodingTypes.PRequest
import org.bertspark.util.io.LocalFileUtil
import org.scalatest.flatspec.AnyFlatSpec

private[simulator] final class RequestMessageGeneratorTest extends AnyFlatSpec {

  it should "Succeed generated messages" in {
    val request1 = "{\"id\": \"45575_2_11770125-207284233\", \"context\": {\"claimType\": \"Cx\", \"age\": 20, \"gender\": \"F\", \"taxonomy\": \"radiology\", \"customer\": \"Cornerstone\", \"client\": \"URAD\", \"procedureCategory\": \"xray\", \"placeOfService\": \"23\", \"dateOfService\": \"04/27/2020\", \"enableMentions\": false, \"EMRCpts\": [{\"order\": 1, \"cpt\": \"73080\", \"modifiers\": [], \"icds\": [], \"quantity\": 1, \"unit\": \"UN\", \"zero\": false}], \"providerId\": \"3\", \"patientId\": \"45575\", \"planId\": \"40/7/utrad-all\", \"extraDict\": \"\", \"unused\": \"\", \"unused2\": \"\", \"notesLocation\": [], \"pipes\": []}, \"notes\": [\"\\r\\n================================================================================\\r\\n\\r\\n                              HASTINGS MEDICAL IMAGING\\r\\n\\r\\nPatient Name: JOSE MARTINEZ NAVARRETE\\r\\nBirth Date: 05/05/1946\\r\\n\\r\\nReferring Doctor: REIMER, CURTIS D\\r\\nReading Doctor: Charge, Tech [/r/nVisit]\\r\\nVisit No.: [/r/nOrder]\\r\\nOrder No.: 223865-1\\r\\nExam Date: 06/22/2022 17:58:02\\r\\nExam: 74177 - CT ABDOMEN PELVIS W IV  ORAL CONTRAST\\r\\n================================================================================\\r\\n\\r\\n~Type of study: Abdomen and pelvic CT with IV contrast.~Clinical history: Right upper quadrant pain, mass and lump.~Multiple axial CT images of the abdomen and pelvis were obtained with IV and oral contrast. Sagittal and coronal reformats were also obtained. Mild cardiac enlargement. Vascular calcification with coronary artery disease. 2 cm right lower lobe nodule. 1 cm right middle lobe nodule. Questionable mucosal thickening near the GE junction. Endoscopy may be helpful. Liver normal. Gallbladder contracted. Common bile duct, pancreas, spleen, left kidney, adrenal glands, IVC normal. Vascular calcification. Aorta is normal cataract. 9.7 cm contrast enhancing right renal mass. This has the appearance of a renal cell carcinoma. No renal vein or IVC involvement. No free fluid or enlarged lymph node. Nonspecific bowel gas pattern. Colonic diverticula. No diverticulitis. Bladder is partially distended. Prostate mildly enlarged. Multilevel degenerative disc disease facet disease lower thoracic and lumbar spine. ~Impression:~1. Large right renal mass. Probably represents renal cell carcinoma. Indeterminate right middle lobe and right lower lobe nodules concerning for metastasis. ~2. Questionable because thickening near GE junction. Endoscopy may be helpful. ~A# H16102F Electronically Signed by Dan Herold, M.D. Jun 22 2022 16:58 CT\\r\\n\"]}"
    val request2 = "{\n  \"id\": \"94936_ROYAL1755946020230306_4_10287456\",\n  \"context\": {\n    \"claimType\": \"\",\n    \"age\": 58,\n    \"gender\": \"F\",\n    \"taxonomy\": \"2085R0202X\",\n    \"placeOfService\": \"22\",\n    \"dateOfService\": \"2022-06-09\",\n    \"providerId\": \"13\",\n    \"patientId\": \"105264\",\n    \"planId\": \"25/radiology/DIAGNOSTIC\",\n    \"customer\": \"CMBS\",\n    \"client\": \"RII\",\n    \"procedureCategory\": \"DIAGNOSTIC\",\n    \"extraDict\": \"\",\n    \"unused\": \"\",\n    \"unused2\": \"\",\n    \"notesLocation\": [],\n    \"pipes\": [],\n    \"enableMentions\": false,\n    \"EMCode\": \"NoEM\",\n    \"EMRCpts\": [\n      {\n        \"order\": 1,\n        \"cpt\": \"G9637\",\n        \"modifiers\": [\"26\"],\n        \"icds\": [],\n        \"quantity\": 1,\n        \"unit\": \"UN\",\n        \"score\": 1.0\n      },\n      {\n        \"order\": 2,\n        \"cpt\": \"70450\",\n        \"modifiers\": [\"26\", \"77\"],\n        \"icds\": [],\n        \"quantity\": 1,\n        \"unit\": \"UN\",\n        \"score\": 1.0\n      }\n    ]\n  },\n  \"notes\": [\"PATIENT: OCONNELL, TRACY\\\\r\\\\nDate of Service: 06/09/21\\\\r\\\\nDI    06/09/21 28894962   202468268CT-21-0023466  RADIOLOGY EXAM RESULTS  Completed   OCONNELL, TRACY D        3260466    CT   921369    OP   Petrus, Leonard V. MD     Yun, David K. MD\\\\r\\\\nEXAM DESCRIPTION:CT Head WO Contrast\\\\r\\\\nCLINICAL HISTORY:Recently diagnosed sinonasal polyposis.  Evaluate for frontal sinus wall dehiscence.\\\\r\\\\nCOMPARISON:None\\\\r\\\\nTECHNIQUE:Non-contrast axial images were obtained from the skull base to the vertex.  Sagittal and coronal re-formations were generated.CTDI/DLP:\\\\r\\\\n57.4/1012.7mGy/mGycmDose reduction technique with one or more of the following methods was performed:  Automated exposure control,adjustment of the mA and/or kv\\\\r\\\\naccording to patient size, use of iterative reconstruction technique.\\\\r\\\\nFINDINGS:The size and shape of the ventricles, basal cisterns and cortical sulci are normal.No focal intra- or extra-axial mass lesion is seen. There is no focal\\\\r\\\\nparenchymal or extra-axial hemorrhage.The attenuation of the cerebral white matter is normal. There is no loss of gray-white matter differentiation.Orbits:\\\\r\\\\nNormalParanasal sinuses: Please refer to maxillofacial CT.Skull base/vault:  NormalIMPRESSION:Normal non-contrast head CT.O: 06/09/21 13:09 YUNDAD: 06/09/21 13:22\\\\r\\\\nPETRLES: 06/09/21 13:22 PETRLEUnit Location: RAD-CAVE04-DT\\\\r\\\\n\\\\r\\\\n\\\\r\\\\n\"\n]\n\n}"
    val pRequest2 = LocalFileUtil.Json.mapper.readValue(request2, classOf[PRequest])
    println(pRequest2.toString)

    val numRepeats = 20
    RequestMessageGenerator.generate(Seq[PRequest](pRequest2), numRepeats)
  }
}
